# Generated by Django 6.0.3 on 2026-03-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('highlight', 'Highlight'), ('table', 'Table')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='ExamNotification.examnotification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='ExamNotification.examnotification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='ExamNotification.examnotification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ExamNotification.notificationtable')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='ExamNotification.notificationtablerow')),
            ],
        ),
    ]
