# Generated by Django 6.0.3 on 2026-08-14 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0011_testimonial_approved_at_testimonial_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Expert', 'Expert')], default='Medium', max_length=10)),
                ('negative_marking_type', models.CharField(choices=[('no_negative', 'No Negative Marking'), ('fixed_per_question', 'Fixed per Wrong Question'), ('percentage_of_marks', 'Percentage of Question Marks')], default='no_negative', max_length=25)),
                ('negative_marking_value', models.FloatField(blank=True, default=0)),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duration in minutes')),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=True)),
                ('instructions', models.TextField(default='Read each question carefully before answering.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='subject_icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MockTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'हिन्दी (Hindi)')], default='en', max_length=10)),
                ('raw_score', models.FloatField(default=0, help_text='Score without negative marking')),
                ('score_with_negative', models.FloatField(default=0, help_text='Score with negative marking applied')),
                ('total_marks', models.FloatField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('skipped_answers', models.PositiveIntegerField(default=0)),
                ('negative_marks_applied', models.FloatField(default=0, help_text='Total negative marks deducted')),
                ('score', models.FloatField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('permanently_deleted', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_paid_user', models.BooleanField(default=False)),
                ('details_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('has_detailed_data', models.BooleanField(default=True)),
                ('exams_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_attempt', to='exams.mocktestattempt')),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='subject_mocktests.mocktest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mock_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.TextField(verbose_name='Question (English)')),
                ('question_hi', models.TextField(blank=True, null=True, verbose_name='Question (Hindi)')),
                ('explanation_en', models.TextField(blank=True, null=True, verbose_name='Explanation (English)')),
                ('explanation_hi', models.TextField(blank=True, null=True, verbose_name='Explanation (Hindi)')),
                ('marks', models.FloatField(default=1)),
                ('negative_marks_override', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Expert', 'Expert')], default='Medium', max_length=10)),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='subject_mocktests.mocktest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=500, verbose_name='Option (English)')),
                ('text_hi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Option (Hindi)')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='subject_mocktests.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='mocktest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to='subject_mocktests.subject'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subject_mocktests.subject')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='mocktest',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_tests', to='subject_mocktests.topic'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.IntegerField(blank=True, help_text='Time taken in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='subject_mocktests.mocktestattempt')),
                ('exams_answer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_answer', to='exams.useranswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='subject_mocktests.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answers', to='subject_mocktests.option')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['user', 'mock_test', 'is_completed'], name='subject_moc_user_id_ce2fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['started_at'], name='subject_moc_started_c5dcb9_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['user', 'is_completed'], name='subject_moc_user_id_143a52_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['mock_test', 'order'], name='subject_moc_mock_te_4afa67_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='subject_moc_difficu_e6ed37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'name')},
        ),
        migrations.AddIndex(
            model_name='mocktest',
            index=models.Index(fields=['subject', 'is_active'], name='subject_moc_subject_606384_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktest',
            index=models.Index(fields=['topic', 'is_active'], name='subject_moc_topic_i_163c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktest',
            index=models.Index(fields=['slug'], name='subject_moc_slug_b61c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt', 'question'], name='subject_moc_attempt_caeb1c_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt', 'is_correct'], name='subject_moc_attempt_ceb6f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('attempt', 'question')},
        ),
    ]
