# Generated by Django 6.0.2 on 2026-03-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_mocktests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmocktest',
            options={'ordering': ['subject', 'topic__order', 'order']},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description_hi',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name_hi',
        ),
        migrations.RemoveField(
            model_name='subjectmocktest',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='subjectmocktest',
            name='instructions_hi',
        ),
        migrations.RemoveField(
            model_name='subjectmocktest',
            name='original_mocktest',
        ),
        migrations.RemoveField(
            model_name='subjectmocktest',
            name='terms_accepted_required',
        ),
        migrations.RemoveField(
            model_name='subjectmocktest',
            name='terms_text',
        ),
        migrations.RemoveField(
            model_name='subjectmocktest',
            name='terms_text_hi',
        ),
        migrations.RemoveField(
            model_name='subjectmocktest',
            name='title_hi',
        ),
        migrations.RemoveField(
            model_name='subjectmocktest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='name_hi',
        ),
        migrations.AddField(
            model_name='subjectmocktest',
            name='old_mocktest_id',
            field=models.IntegerField(default=2, help_text='ID of the MockTest in exams app (check exams_mocktest table)'),
            preserve_default=False,
        ),
    ]
