# Generated by Django 6.0.3 on 2026-03-14 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('subject_mocktests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mocktest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mocktestattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='mocktestattempt',
            name='exams_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_attempt', to='exams.mocktestattempt'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='exams_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_answer', to='exams.useranswer'),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='instructions',
            field=models.TextField(default='Read each question carefully before answering.'),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='negative_marking_value',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='negative_marks_override',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
