# Generated by Django 6.0.3 on 2026-03-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_mocktests', '0002_alter_mocktest_options_alter_mocktestattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestattempt',
            name='negative_marks_applied',
            field=models.FloatField(default=0, help_text='Total negative marks deducted'),
        ),
        migrations.AddField(
            model_name='mocktestattempt',
            name='raw_score',
            field=models.FloatField(default=0, help_text='Score without negative marking'),
        ),
        migrations.AddField(
            model_name='mocktestattempt',
            name='score_with_negative',
            field=models.FloatField(default=0, help_text='Score with negative marking applied'),
        ),
    ]
