# Generated by Django 6.0.2 on 2026-03-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_mocktests', '0002_alter_subjectmocktest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmocktest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subjectmocktest',
            name='old_mocktest_id',
        ),
        migrations.AddField(
            model_name='subjectmocktest',
            name='mocktest_id',
            field=models.IntegerField(default=2, help_text='ID of the MockTest in exams app'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
