# Generated by Django 6.0.3 on 2026-03-14 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='category_logos/')),
            ],
            options={
                'verbose_name_plural': 'Exam Categories',
            },
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('negative_marking_type', models.CharField(choices=[('no_negative', 'No Negative Marking'), ('fixed_per_question', 'Fixed per Wrong Question'), ('percentage_of_marks', 'Percentage of Question Marks')], default='no_negative', max_length=25)),
                ('negative_marking_value', models.FloatField(blank=True, default=0, help_text='Negative marks or percentage depending on type')),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duration in minutes')),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='Time limit per attempt in minutes')),
                ('total_marks', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'हिन्दी (Hindi)')], default='en', help_text='Language selected by user for this attempt', max_length=10)),
                ('score', models.FloatField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('skipped_answers', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False, help_text='Detailed answers archived, only summary kept for rankings')),
                ('permanently_deleted', models.BooleanField(default=False, help_text='Attempt permanently deleted from database')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_paid_user', models.BooleanField(default=False, help_text='Whether this attempt belongs to a paid user')),
                ('details_deleted_at', models.DateTimeField(blank=True, help_text='When detailed answers were deleted', null=True)),
                ('has_detailed_data', models.BooleanField(default=True, help_text='Whether detailed answers still exist')),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.mocktest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mock Test Attempt',
                'verbose_name_plural': 'Mock Test Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.TextField(verbose_name='Question (English)')),
                ('question_hi', models.TextField(blank=True, null=True, verbose_name='Question (Hindi)')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Explanation (English)')),
                ('explanation_hi', models.TextField(blank=True, null=True, verbose_name='Explanation (Hindi)')),
                ('marks', models.FloatField(default=1, help_text='Marks for this question')),
                ('negative_marks', models.FloatField(blank=True, default=0.25, help_text="Override test's negative marking for this question. Leave blank to use test default.", null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Question order in test')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', help_text='Difficulty level of the question', max_length=10)),
                ('topic', models.CharField(blank=True, help_text='e.g., Algebra, Grammar, Modern History', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.mocktest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=255, verbose_name='Option (English)')),
                ('text_hi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Option (Hindi)')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Option order (1,2,3,4)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='sub_icons/')),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='exams.examcategory')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.AddField(
            model_name='mocktest',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_tests', to='exams.subcategory'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_question_no', models.PositiveIntegerField()),
                ('end_question_no', models.PositiveIntegerField()),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='exams.mocktest')),
            ],
            options={
                'ordering': ['start_question_no'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.subject'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Share your experience with our platform', max_length=500)),
                ('stars', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('achievement', models.CharField(blank=True, help_text="e.g., 'Selected in UPSC 2023', 'Scored 95% in JEE'", max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this testimonial as featured')),
                ('is_active', models.BooleanField(default=False, help_text='Only active testimonials will be displayed')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['display_order', '-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.IntegerField(blank=True, help_text='Time taken in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.mocktestattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='exams.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answers', to='exams.option')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['user', 'mock_test', 'is_completed'], name='exams_mockt_user_id_f54e34_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['started_at'], name='exams_mockt_started_92bc2d_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['submitted_at'], name='exams_mockt_submitt_b7f46d_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['is_archived'], name='exams_mockt_is_arch_96f52d_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['is_paid_user', 'submitted_at', 'has_detailed_data'], name='exams_mockt_is_paid_6d7b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt', 'question'], name='exams_usera_attempt_e8743e_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['is_correct'], name='exams_usera_is_corr_6224b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('attempt', 'question')},
        ),
    ]
