# Generated by Django 6.0.2 on 2026-02-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quizscore',
            name='exams_quizs_user_id_e5080d_idx',
        ),
        migrations.RemoveIndex(
            model_name='quizscore',
            name='exams_quizs_percent_ae60d7_idx',
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='mocktestattempt',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='quizscore',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='quizscore',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quizscore',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserRanking',
        ),
        migrations.DeleteModel(
            name='QuizScore',
        ),
    ]
