# Generated by Django 6.0.3 on 2026-03-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktest',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='negative_marking_type',
            field=models.CharField(choices=[('no_negative', 'No Negative Marking'), ('fixed_per_question', 'Fixed per Wrong Question'), ('percentage_of_marks', 'Percentage of Question Marks')], default='no_negative', max_length=25),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='negative_marking_value',
            field=models.FloatField(blank=True, default=0, help_text='Negative marks or percentage depending on type'),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, help_text='Time limit per attempt in minutes'),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
    ]
