# Generated by Django 6.0.2 on 2026-03-07 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mocktestattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Mock Test Attempt', 'verbose_name_plural': 'Mock Test Attempts'},
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_hi',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation (Hindi)'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text_en',
            field=models.CharField(max_length=255, verbose_name='Option (English)'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text_hi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Option (Hindi)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation (English)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='negative_marks',
            field=models.FloatField(blank=True, default=0.25, help_text="Override test's negative marking for this question. Leave blank to use test default.", null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_en',
            field=models.TextField(verbose_name='Question (English)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_hi',
            field=models.TextField(blank=True, null=True, verbose_name='Question (Hindi)'),
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['user', 'mock_test', 'is_completed'], name='exams_mockt_user_id_f54e34_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['started_at'], name='exams_mockt_started_92bc2d_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['submitted_at'], name='exams_mockt_submitt_b7f46d_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['is_archived'], name='exams_mockt_is_arch_96f52d_idx'),
        ),
    ]
