# Generated by Django 6.0.2 on 2026-02-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_quizscore_exams_quizs_user_id_e5080d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', help_text='Difficulty level of the question', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, help_text='e.g., Algebra, Grammar, Modern History', max_length=200, null=True),
        ),
    ]
