# Generated by Django 6.0.3 on 2026-03-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_mocktest_difficulty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mocktestattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['display_order', '-is_featured', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='mocktestattempt',
            name='exams_mockt_is_arch_96f52d_idx',
        ),
        migrations.RemoveIndex(
            model_name='mocktestattempt',
            name='exams_mockt_is_paid_6d7b3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='useranswer',
            name='exams_usera_attempt_e8743e_idx',
        ),
        migrations.RemoveIndex(
            model_name='useranswer',
            name='exams_usera_is_corr_6224b4_idx',
        ),
        migrations.AddField(
            model_name='mocktest',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, help_text='Total number of questions'),
        ),
        migrations.AddField(
            model_name='mocktestattempt',
            name='negative_marks_applied',
            field=models.FloatField(default=0, help_text='Total negative marks deducted'),
        ),
        migrations.AddField(
            model_name='mocktestattempt',
            name='raw_score',
            field=models.FloatField(default=0, help_text='Score without negative marking'),
        ),
        migrations.AddField(
            model_name='mocktestattempt',
            name='score_with_negative',
            field=models.FloatField(default=0, help_text='Score with negative marking applied'),
        ),
        migrations.AddField(
            model_name='question',
            name='override_test_negative',
            field=models.BooleanField(default=False, help_text="Check to use this question's negative marks instead of test defaults"),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='negative_marking_type',
            field=models.CharField(choices=[('no_negative', 'No Negative Marking'), ('fixed_per_question', 'Fixed per Wrong Question'), ('percentage_of_marks', 'Percentage of Question Marks'), ('per_question', 'Per Question Negative Marking')], default='no_negative', max_length=25),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='total_marks',
            field=models.FloatField(default=0, help_text='Total marks for the test'),
        ),
        migrations.AlterField(
            model_name='mocktestattempt',
            name='details_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mocktestattempt',
            name='has_detailed_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mocktestattempt',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mocktestattempt',
            name='is_paid_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mocktestattempt',
            name='permanently_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='negative_marks',
            field=models.FloatField(blank=True, help_text='Negative marks for this question. If blank, uses difficulty-based default or test default.', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='achievement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='time_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='mocktestattempt',
            name='score',
        ),
    ]
