# Generated by Django 6.0.3 on 2026-03-11 14:16

from django.db import migrations
from django.db.models import Count


def fix_all_duplicate_options(apps, schema_editor):
    Option = apps.get_model('exams', 'Option')
    
    # Find all question_id and order combinations that have duplicates
    duplicates = Option.objects.values('question_id', 'order').annotate(
        count=Count('id')
    ).filter(count__gt=1)
    
    # For each duplicate group, keep the first one and delete others
    for duplicate in duplicates:
        question_id = duplicate['question_id']
        order = duplicate['order']
        
        # Get all options with this question_id and order
        options = Option.objects.filter(
            question_id=question_id, 
            order=order
        ).order_by('id')  # Order by ID to keep the oldest
        
        if options.count() > 1:
            # Keep the first one, delete the rest
            first = options.first()
            options.exclude(id=first.id).delete()
            print(f"Fixed duplicates for question {question_id}, order {order}")


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_mocktest_difficulty_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_all_duplicate_options),
    ]
