# Generated by Django 6.0.3 on 2026-03-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_mocktest_difficulty_and_more'),
    ]

    operations = [
    ]
