# Generated by Django 6.0.3 on 2026-03-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_mocktestattempt_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, help_text='e.g., General, Account, Test Related', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
