# Generated by Django 6.0.3 on 2026-03-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on FAQ page'),
        ),
    ]
