# Generated by Django 6.0.2 on 2026-02-22 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_testimonial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['display_order', '-is_featured', '-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='order',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='user_name',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='achievement',
            field=models.CharField(blank=True, help_text="e.g., 'Selected in UPSC 2023', 'Scored 95% in JEE'", max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active testimonials will be displayed'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this testimonial as featured'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='stars',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(help_text='Share your experience with our platform', max_length=500),
        ),
    ]
