# Generated by Django 6.0.2 on 2026-02-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_testimonial_options_remove_testimonial_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only active testimonials will be displayed'),
        ),
    ]
