# Generated by Django 6.0.3 on 2026-07-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcategory',
            name='about_content',
            field=models.TextField(blank=True, help_text='Detailed about content with HTML support (headings, paragraphs, lists)', null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Image for the about section', null=True, upload_to='categories/about/'),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='about_title',
            field=models.CharField(blank=True, help_text='Title for the about section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Main banner image for the category page', null=True, upload_to='categories/banners/'),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='banner_subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle for banner', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='banner_title',
            field=models.CharField(blank=True, help_text='Optional custom title for banner', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='exam_pattern_content',
            field=models.TextField(blank=True, help_text='Exam pattern details with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='exam_pattern_image',
            field=models.ImageField(blank=True, help_text='Image for exam pattern section', null=True, upload_to='categories/exam_pattern/'),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='exam_pattern_title',
            field=models.CharField(blank=True, default='Exam Pattern', help_text='Title for exam pattern section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='extra_section_1_content',
            field=models.TextField(blank=True, help_text='Content for extra section 1 with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='extra_section_1_image',
            field=models.ImageField(blank=True, help_text='Image for extra section 1', null=True, upload_to='categories/extra/'),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='extra_section_1_title',
            field=models.CharField(blank=True, help_text='Title for extra section 1', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='extra_section_2_content',
            field=models.TextField(blank=True, help_text='Content for extra section 2 with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='extra_section_2_image',
            field=models.ImageField(blank=True, help_text='Image for extra section 2', null=True, upload_to='categories/extra/'),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='extra_section_2_title',
            field=models.CharField(blank=True, help_text='Title for extra section 2', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='features_content',
            field=models.TextField(blank=True, help_text='Features content with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='features_image',
            field=models.ImageField(blank=True, help_text='Image for the features section', null=True, upload_to='categories/features/'),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='features_title',
            field=models.CharField(blank=True, help_text='Title for the features section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='syllabus_content',
            field=models.TextField(blank=True, help_text='Syllabus details with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='syllabus_image',
            field=models.ImageField(blank=True, help_text='Image for syllabus section', null=True, upload_to='categories/syllabus/'),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='syllabus_title',
            field=models.CharField(blank=True, default='Complete Syllabus', help_text='Title for syllabus section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='tips_content',
            field=models.TextField(blank=True, help_text='Preparation tips with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='tips_image',
            field=models.ImageField(blank=True, help_text='Image for preparation tips section', null=True, upload_to='categories/tips/'),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='tips_title',
            field=models.CharField(blank=True, default='Preparation Tips', help_text='Title for preparation tips section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Main banner image for the test page', null=True, upload_to='mocktests/banners/'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='banner_subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle for banner', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='banner_title',
            field=models.CharField(blank=True, help_text='Optional custom title for banner', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='expectations_content',
            field=models.TextField(blank=True, help_text='What to expect content with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='expectations_image',
            field=models.ImageField(blank=True, help_text='Image for expectations section', null=True, upload_to='mocktests/expectations/'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='expectations_title',
            field=models.CharField(blank=True, default='What to Expect', help_text='Title for expectations section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='extra_section_1_content',
            field=models.TextField(blank=True, help_text='Content for extra section with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='extra_section_1_image',
            field=models.ImageField(blank=True, help_text='Image for extra section', null=True, upload_to='mocktests/extra/'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='extra_section_1_title',
            field=models.CharField(blank=True, help_text='Title for extra section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='features_content',
            field=models.TextField(blank=True, help_text='Features content with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='features_image',
            field=models.ImageField(blank=True, help_text='Image for features section', null=True, upload_to='mocktests/features/'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='features_title',
            field=models.CharField(blank=True, default='Key Features', help_text='Title for features section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='overview_content',
            field=models.TextField(blank=True, help_text='Overview content with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='overview_image',
            field=models.ImageField(blank=True, help_text='Image for overview section', null=True, upload_to='mocktests/overview/'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='overview_title',
            field=models.CharField(blank=True, default='Test Overview', help_text='Title for overview section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='tips_content',
            field=models.TextField(blank=True, help_text='Tips content with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='tips_image',
            field=models.ImageField(blank=True, help_text='Image for tips section', null=True, upload_to='mocktests/tips/'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='tips_title',
            field=models.CharField(blank=True, default='Tips & Strategies', help_text='Title for tips section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='about_content',
            field=models.TextField(blank=True, help_text='Detailed about content with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Image for the about section', null=True, upload_to='subcategories/about/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='about_title',
            field=models.CharField(blank=True, help_text='Title for the about section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Main banner image for the subcategory page', null=True, upload_to='subcategories/banners/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='banner_subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle for banner', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='banner_title',
            field=models.CharField(blank=True, help_text='Optional custom title for banner', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='extra_section_1_content',
            field=models.TextField(blank=True, help_text='Content for extra section with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='extra_section_1_image',
            field=models.ImageField(blank=True, help_text='Image for extra section', null=True, upload_to='subcategories/extra/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='extra_section_1_title',
            field=models.CharField(blank=True, help_text='Title for extra section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='syllabus_content',
            field=models.TextField(blank=True, help_text='Syllabus or key topics with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='syllabus_image',
            field=models.ImageField(blank=True, help_text='Image for syllabus section', null=True, upload_to='subcategories/syllabus/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='syllabus_title',
            field=models.CharField(blank=True, default='Key Topics', help_text='Title for syllabus/topics section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='tips_content',
            field=models.TextField(blank=True, help_text='Study tips with HTML support', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='tips_image',
            field=models.ImageField(blank=True, help_text='Image for tips section', null=True, upload_to='subcategories/tips/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='tips_title',
            field=models.CharField(blank=True, default='Study Tips', help_text='Title for study tips section', max_length=200, null=True),
        ),
    ]
