# Generated by Django 6.0.3 on 2026-07-28 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_remove_examcategory_about_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcategory',
            name='banner_subtitle_hi',
            field=models.CharField(blank=True, help_text='Banner subtitle in Hindi', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='banner_title_hi',
            field=models.CharField(blank=True, help_text='Banner title in Hindi', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='description_hi',
            field=models.TextField(blank=True, help_text='Description in Hindi', null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='syllabus_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='syllabus_description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='syllabus_heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examcategory',
            name='syllabus_heading_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='banner_subtitle_hi',
            field=models.CharField(blank=True, help_text='Banner subtitle in Hindi', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='banner_title_hi',
            field=models.CharField(blank=True, help_text='Banner title in Hindi', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='syllabus_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='syllabus_description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='syllabus_heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='syllabus_heading_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='title_hi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='total_sections',
            field=models.PositiveIntegerField(default=1, help_text='Number of sections'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='banner_subtitle_hi',
            field=models.CharField(blank=True, help_text='Banner subtitle in Hindi', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='banner_title_hi',
            field=models.CharField(blank=True, help_text='Banner title in Hindi', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='syllabus_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='syllabus_description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='syllabus_heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='syllabus_heading_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examcategory',
            name='custom_content',
            field=models.JSONField(blank=True, default=list, help_text='[DEPRECATED] Use ContentBlock model instead.'),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='custom_content',
            field=models.JSONField(blank=True, default=list, help_text='[DEPRECATED] Use ContentBlock model instead.'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='custom_content',
            field=models.JSONField(blank=True, default=list, help_text='[DEPRECATED] Use ContentBlock model instead.'),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('image', 'Image'), ('table', 'Table'), ('list', 'List'), ('card', 'Card'), ('accordion', 'Accordion'), ('tabs', 'Tabs'), ('video', 'Video'), ('divider', 'Divider'), ('custom', 'Custom HTML')], default='paragraph', max_length=20)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title (English)')),
                ('title_hi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title (Hindi)')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Content (English)')),
                ('content_hi', models.TextField(blank=True, null=True, verbose_name='Content (Hindi)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_images/')),
                ('image_alt_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image Alt Text (English)')),
                ('image_alt_hi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image Alt Text (Hindi)')),
                ('table_data', models.JSONField(blank=True, default=list, help_text='JSON format for tables:\n        {\n            "headers": ["Header 1", "Header 2"],\n            "rows": [\n                ["Row 1 Col 1", "Row 1 Col 2"],\n                ["Row 2 Col 1", "Row 2 Col 2"]\n            ]\n        }\n        ')),
                ('list_items', models.JSONField(blank=True, default=list, help_text='Array of list items')),
                ('css_class', models.CharField(blank=True, help_text='Custom CSS classes', max_length=200, null=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50, null=True)),
                ('bg_color', models.CharField(blank=True, help_text='Background color (hex or tailwind class)', max_length=50, null=True)),
                ('text_color', models.CharField(blank=True, help_text='Text color (hex or tailwind class)', max_length=50, null=True)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Highlight this block')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible_on_mobile', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='exams.examcategory')),
                ('mock_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='exams.mocktest')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='exams.subcategory')),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['order'],
            },
        ),
    ]
