# Generated by Django 6.0.3 on 2026-07-28 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_examcategory_banner_subtitle_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcategory',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Hindi)'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Hindi)'),
        ),
        migrations.AlterField(
            model_name='examcategory',
            name='custom_content',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='examcategory',
            name='description_hi',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='custom_content',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='description_hi',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='title_hi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Hindi)'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='custom_content',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description_hi',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Hindi)'),
        ),
        migrations.CreateModel(
            name='CategoryContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Section Title (English)')),
                ('section_title_hi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Section Title (Hindi)')),
                ('content_en', models.TextField(blank=True, help_text='You can use HTML: <h2>, <p>, <ul>, <ol>, <table>, etc.', null=True, verbose_name='Content (English)')),
                ('content_hi', models.TextField(blank=True, help_text='You can use HTML: <h2>, <p>, <ul>, <ol>, <table>, etc.', null=True, verbose_name='Content (Hindi)')),
                ('image', models.ImageField(blank=True, help_text='Optional image for this section', null=True, upload_to='section_images/')),
                ('image_alt_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image Alt Text (English)')),
                ('image_alt_hi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image Alt Text (Hindi)')),
                ('table_data', models.JSONField(blank=True, default=dict, help_text='Table data in JSON format:\n        {\n            "headers": ["Column 1", "Column 2", "Column 3"],\n            "rows": [\n                ["Row 1 Col 1", "Row 1 Col 2", "Row 1 Col 3"],\n                ["Row 2 Col 1", "Row 2 Col 2", "Row 2 Col 3"]\n            ]\n        }')),
                ('list_items', models.JSONField(blank=True, default=list, help_text='List items as JSON array: ["Item 1", "Item 2", "Item 3"]')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this section')),
                ('is_active', models.BooleanField(default=True, help_text='Show this section')),
                ('background_color', models.CharField(blank=True, help_text='e.g., #f3f4f6 or gray-100', max_length=50, null=True)),
                ('text_color', models.CharField(blank=True, help_text='e.g., #1f2937 or text-gray-800', max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='exams.examcategory')),
            ],
            options={
                'verbose_name': 'Category Content Section',
                'verbose_name_plural': 'Category Content Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MockTestContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Section Title (English)')),
                ('section_title_hi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Section Title (Hindi)')),
                ('content_en', models.TextField(blank=True, help_text='You can use HTML: <h2>, <p>, <ul>, <ol>, <table>, etc.', null=True, verbose_name='Content (English)')),
                ('content_hi', models.TextField(blank=True, help_text='You can use HTML: <h2>, <p>, <ul>, <ol>, <table>, etc.', null=True, verbose_name='Content (Hindi)')),
                ('image', models.ImageField(blank=True, help_text='Optional image for this section', null=True, upload_to='section_images/')),
                ('image_alt_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image Alt Text (English)')),
                ('image_alt_hi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image Alt Text (Hindi)')),
                ('table_data', models.JSONField(blank=True, default=dict, help_text='Table data in JSON format:\n        {\n            "headers": ["Column 1", "Column 2", "Column 3"],\n            "rows": [\n                ["Row 1 Col 1", "Row 1 Col 2", "Row 1 Col 3"],\n                ["Row 2 Col 1", "Row 2 Col 2", "Row 2 Col 3"]\n            ]\n        }')),
                ('list_items', models.JSONField(blank=True, default=list, help_text='List items as JSON array: ["Item 1", "Item 2", "Item 3"]')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this section')),
                ('is_active', models.BooleanField(default=True, help_text='Show this section')),
                ('background_color', models.CharField(blank=True, help_text='e.g., #f3f4f6 or gray-100', max_length=50, null=True)),
                ('text_color', models.CharField(blank=True, help_text='e.g., #1f2937 or text-gray-800', max_length=50, null=True)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='exams.mocktest')),
            ],
            options={
                'verbose_name': 'MockTest Content Section',
                'verbose_name_plural': 'MockTest Content Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategoryContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Section Title (English)')),
                ('section_title_hi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Section Title (Hindi)')),
                ('content_en', models.TextField(blank=True, help_text='You can use HTML: <h2>, <p>, <ul>, <ol>, <table>, etc.', null=True, verbose_name='Content (English)')),
                ('content_hi', models.TextField(blank=True, help_text='You can use HTML: <h2>, <p>, <ul>, <ol>, <table>, etc.', null=True, verbose_name='Content (Hindi)')),
                ('image', models.ImageField(blank=True, help_text='Optional image for this section', null=True, upload_to='section_images/')),
                ('image_alt_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image Alt Text (English)')),
                ('image_alt_hi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image Alt Text (Hindi)')),
                ('table_data', models.JSONField(blank=True, default=dict, help_text='Table data in JSON format:\n        {\n            "headers": ["Column 1", "Column 2", "Column 3"],\n            "rows": [\n                ["Row 1 Col 1", "Row 1 Col 2", "Row 1 Col 3"],\n                ["Row 2 Col 1", "Row 2 Col 2", "Row 2 Col 3"]\n            ]\n        }')),
                ('list_items', models.JSONField(blank=True, default=list, help_text='List items as JSON array: ["Item 1", "Item 2", "Item 3"]')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this section')),
                ('is_active', models.BooleanField(default=True, help_text='Show this section')),
                ('background_color', models.CharField(blank=True, help_text='e.g., #f3f4f6 or gray-100', max_length=50, null=True)),
                ('text_color', models.CharField(blank=True, help_text='e.g., #1f2937 or text-gray-800', max_length=50, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='exams.subcategory')),
            ],
            options={
                'verbose_name': 'SubCategory Content Section',
                'verbose_name_plural': 'SubCategory Content Sections',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ContentBlock',
        ),
    ]
