# Generated by Django 6.0.3 on 2026-08-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_testimonial_approved_at_testimonial_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this category on the site'),
        ),
    ]
