# Generated by Django 6.0.3 on 2026-08-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_examcategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this subcategory on the site'),
        ),
    ]
