# Generated by Django 6.0.3 on 2026-08-15 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_subcategory_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('payment_gateway_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('upi', 'UPI'), ('cod', 'Cash on Delivery')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('items', models.JSONField(default=list, help_text='List of purchased items')),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_reason', models.TextField(blank=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('subject', 'Exam Category'), ('topic', 'Sub Category'), ('mocktest', 'Mock Test')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('pricing_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid (One-time)'), ('subscription', 'Subscription'), ('trial', 'Trial')], default='free', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subscription_duration_days', models.PositiveIntegerField(blank=True, help_text='For subscription: duration in days (e.g., 30 for 1 month)', null=True)),
                ('trial_duration_days', models.PositiveIntegerField(blank=True, help_text='Trial duration in days (e.g., 7 for 7-day trial)', null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5)),
                ('discount_start_date', models.DateTimeField(blank=True, null=True)),
                ('discount_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_payment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['content_type', 'created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id', 'is_active'], name='exams_prici_content_3adc1c_idx'), models.Index(fields=['pricing_type', 'is_active'], name='exams_prici_pricing_10f216_idx')],
                'unique_together': {('content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField()),
                ('is_unlimited', models.BooleanField(default=True, help_text='If True, access to all content')),
                ('allowed_content_types', models.JSONField(blank=True, default=list, help_text='List of content types allowed')),
                ('allowed_content_ids', models.JSONField(blank=True, default=list, help_text='List of specific content IDs')),
                ('features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='exams.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('payment_init', 'Payment Initiated'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund', 'Refund'), ('access_granted', 'Access Granted'), ('access_revoked', 'Access Revoked'), ('subscription_created', 'Subscription Created'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_cancelled', 'Subscription Cancelled'), ('trial_started', 'Trial Started'), ('trial_expired', 'Trial Expired')], max_length=30)),
                ('content_type', models.CharField(blank=True, max_length=20, null=True)),
                ('content_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserContentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('subject', 'Exam Category'), ('topic', 'Sub Category'), ('mocktest', 'Mock Test')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('access_type', models.CharField(choices=[('one_time', 'One-time Purchase'), ('subscription', 'Subscription'), ('free', 'Free Access'), ('trial', 'Trial Access'), ('lifetime', 'Lifetime Access')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_accesses', to='exams.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='exams_payme_user_id_8a254d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='exams_payme_payment_544d30_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order_id'], name='exams_payme_order_i_0542fc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='exams_payme_created_5fccb5_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='exams_subsc_user_id_f638ec_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['expiry_date'], name='exams_subsc_expiry__3973a6_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['user', 'action'], name='exams_trans_user_id_2a96b9_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['created_at'], name='exams_trans_created_cd41fe_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontentaccess',
            index=models.Index(fields=['user', 'content_type', 'content_id'], name='exams_userc_user_id_93ea72_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontentaccess',
            index=models.Index(fields=['status', 'expiry_date'], name='exams_userc_status_320558_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontentaccess',
            index=models.Index(fields=['user', 'status'], name='exams_userc_user_id_d70829_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercontentaccess',
            unique_together={('user', 'content_type', 'content_id')},
        ),
    ]
