# Generated by Django 6.0.3 on 2026-08-15 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_payment_pricingconfig_subscription_transactionlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontentaccess',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_content_accesses', to='exams.payment'),
        ),
        migrations.AlterField(
            model_name='usercontentaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_content_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
