# Generated by Django 6.0.3 on 2026-08-01 10:58

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Part Name')),
                ('name_hi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Part Name (Hindi)')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_hi', models.TextField(blank=True, verbose_name='Description (Hindi)')),
                ('comprehensive_content', models.TextField(blank=True, verbose_name='Comprehensive Content')),
                ('comprehensive_content_hi', models.TextField(blank=True, verbose_name='Comprehensive Content (Hindi)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0, help_text='Number of views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Subject Name')),
                ('name_hi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Name (Hindi)')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_hi', models.TextField(blank=True, verbose_name='Description (Hindi)')),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-book')", max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subjects/')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('question_hi', models.TextField(blank=True, null=True, verbose_name='Question (Hindi)')),
                ('answer', ckeditor.fields.RichTextField(blank=True, verbose_name='Answer')),
                ('answer_hi', ckeditor.fields.RichTextField(blank=True, verbose_name='Answer (Hindi)')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0, help_text='Number of views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='QA.part')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='questions/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('caption_hi', models.CharField(blank=True, max_length=200, verbose_name='Caption (Hindi)')),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='QA.question')),
            ],
            options={
                'verbose_name': 'Question Image',
                'verbose_name_plural': 'Question Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_data', models.TextField(help_text='Enter table HTML', verbose_name='Table Data (HTML)')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('caption_hi', models.CharField(blank=True, max_length=200, verbose_name='Caption (Hindi)')),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='QA.question')),
            ],
            options={
                'verbose_name': 'Question Table',
                'verbose_name_plural': 'Question Tables',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Topic Name')),
                ('name_hi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Topic Name (Hindi)')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_hi', models.TextField(blank=True, verbose_name='Description (Hindi)')),
                ('comprehensive_content', models.TextField(blank=True, verbose_name='Comprehensive Content')),
                ('comprehensive_content_hi', models.TextField(blank=True, verbose_name='Comprehensive Content (Hindi)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='QA.subject')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='QA.topic'),
        ),
        migrations.CreateModel(
            name='ComprehensiveContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('subject', 'Subject'), ('topic', 'Topic'), ('part', 'Part')], max_length=20)),
                ('heading', models.CharField(max_length=200, verbose_name='Heading')),
                ('heading_hi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Heading (Hindi)')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('content_hi', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content (Hindi)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_contents', to='QA.part')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_contents', to='QA.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_contents', to='QA.topic')),
            ],
            options={
                'verbose_name': 'Comprehensive Content',
                'verbose_name_plural': 'Comprehensive Contents',
                'ordering': ['order'],
            },
        ),
    ]
