# Generated by Django 6.0.3 on 2026-08-06 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('name_hi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category Name (Hindi)')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code (e.g., #6366f1)', max_length=20)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-calculator')", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question Category',
                'verbose_name_plural': 'Question Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when this question was published'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('numerical', 'Numerical'), ('descriptive', 'Descriptive'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('match', 'Match the Following')], default='descriptive', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags for advanced filtering (e.g., ["important", "repeated"])'),
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='questions', to='QA.questioncategory'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['published_date'], name='QA_question_publish_efed91_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='QA_question_difficu_b56b08_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='QA_question_questio_966abd_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='QA_question_is_acti_e14f3f_idx'),
        ),
    ]
