# Generated by Django 6.0.3 on 2026-08-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0002_questioncategory_question_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='comprehensive_content',
        ),
        migrations.RemoveField(
            model_name='part',
            name='comprehensive_content_hi',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='comprehensive_content',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='comprehensive_content_hi',
        ),
        migrations.AddField(
            model_name='part',
            name='content',
            field=models.TextField(blank=True, help_text='\n        Use simple markup for rich content:\n        \n        For tables:\n        [table]\n        Name | Age | City | Occupation\n        John | 25 | NYC | Engineer\n        Jane | 30 | LA | Designer\n        Mike | 35 | CHI | Developer\n        [/table]\n        \n        For lists:\n        [list]\n        * Item 1\n        * Item 2\n        * Item 3\n        [/list]\n        \n        For images:\n        [image: path/to/image.jpg]Caption text[/image]\n        \n        For code blocks:\n        [code]\n        print("Hello World")\n        [/code]\n        \n        For quotes:\n        [quote]Quote text here[/quote]\n        \n        For highlights:\n        [highlight]Important text[/highlight]\n        ', verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='part',
            name='content_hi',
            field=models.TextField(blank=True, help_text='Hindi version of the content', null=True, verbose_name='Content (Hindi)'),
        ),
    ]
