# Generated by Django 6.0.3 on 2026-08-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0003_remove_part_comprehensive_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags for advanced filtering'),
        ),
    ]
