# Generated by Django 6.0.3 on 2026-03-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAffairsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CurrentAffairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(help_text='News content - you can add tables using HTML')),
                ('summary', models.TextField(help_text='Brief summary for card view', max_length=500)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='current_affairs/')),
                ('image_caption', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('news_date', models.DateField(help_text='Date when the news occurred')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_weight', models.PositiveIntegerField(default=1, help_text='Higher weight = more chances to appear in random selection')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='CurrentAffairs.currentaffairscategory')),
            ],
            options={
                'verbose_name_plural': 'Current Affairs',
                'ordering': ['-news_date', '-id'],
                'indexes': [models.Index(fields=['-news_date', 'status'], name='CurrentAffa_news_da_f40242_idx'), models.Index(fields=['category', '-news_date'], name='CurrentAffa_categor_554c1a_idx')],
            },
        ),
    ]
